apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-managed
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/argocd-self-managed.git'
    targetRevision: main
    path: '.'
    kustomize:
      # You can include kustomize-specific options here if needed
      # For now, leave it empty
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
