apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - manifests/deployments/argocd-deployments.yaml
  - manifests/services/argocd-services.yaml
  - manifests/configmaps/argocd-configmaps.yaml
  - manifests/secrets/argocd-secrets.yaml
